In [3]:
from utils import *

In [37]:
x = np.random.random_integers(0,100,3).reshape(1,-1)
y = np.random.random_integers(0,100,3).reshape(1,-1)

x = normalize(x)
y = normalize(y)

C:\Users\Mark Risk\AppData\Local\Temp\ipykernel_4484\1028404106.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  x = np.random.random_integers(0,100,3).reshape(1,-1)
C:\Users\Mark Risk\AppData\Local\Temp\ipykernel_4484\1028404106.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  y = np.random.random_integers(0,100,3).reshape(1,-1)


In [38]:
print(x)
print(y)

[[0.59697772 0.3169141  0.73700953]]
[[0.69707148 0.32065288 0.64130576]]


In [39]:
for l in range(0,100):
    l = 2 + l/100
    print(l)
    k1 = Matern(length_scale=l, nu = 0.5)
    k2 = NTK(depth = 3, c = 2.0, bias = 2.0)
    print(k1(x,y))
    print(k2(x,y))

2.0
[[0.93307704]]
[[0.93524143]]
2.01
[[0.93339865]]
[[0.93524143]]
2.02
[[0.93371718]]
[[0.93524143]]
2.03
[[0.93403268]]
[[0.93524143]]
2.04
[[0.93434519]]
[[0.93524143]]
2.05
[[0.93465476]]
[[0.93524143]]
2.06
[[0.93496142]]
[[0.93524143]]
2.07
[[0.93526522]]
[[0.93524143]]
2.08
[[0.9355662]]
[[0.93524143]]
2.09
[[0.93586439]]
[[0.93524143]]
2.1
[[0.93615983]]
[[0.93524143]]
2.11
[[0.93645257]]
[[0.93524143]]
2.12
[[0.93674263]]
[[0.93524143]]
2.13
[[0.93703006]]
[[0.93524143]]
2.14
[[0.93731489]]
[[0.93524143]]
2.15
[[0.93759716]]
[[0.93524143]]
2.16
[[0.93787689]]
[[0.93524143]]
2.17
[[0.93815413]]
[[0.93524143]]
2.18
[[0.93842891]]
[[0.93524143]]
2.19
[[0.93870126]]
[[0.93524143]]
2.2
[[0.93897121]]
[[0.93524143]]
2.21
[[0.93923879]]
[[0.93524143]]
2.22
[[0.93950404]]
[[0.93524143]]
2.23
[[0.93976698]]
[[0.93524143]]
2.24
[[0.94002765]]
[[0.93524143]]
2.25
[[0.94028607]]
[[0.93524143]]
2.26
[[0.94054228]]
[[0.93524143]]
2.27
[[0.94079629]]
[[0.93524143]]
2.2800000000000002
[[0.9

In [61]:
k2 = NTK(depth = 3, c = 2.0, bias = 2.05)

In [73]:
for b in range(0,100):
    bias = b
    k2 = NTK(depth = 100, c = 2.0, bias = bias)
    print(f"bias = {bias}")
    lengthscales = np.zeros([100])
    for i in range(0,100):
        x2 = np.random.randint(0,100,3).reshape(1,-1)
        y2 = np.random.randint(0,100,3).reshape(1,-1)

        x2 = normalize(x2)
        y2 = normalize(y2)

        K = k2(x2,y2)
        lengthscales[i] = - np.linalg.norm(x2-y2) / np.log(k2(x2,y2))
    print(f"mean(lengthscales) = {np.mean(lengthscales)}")
    print(f"var(lengthscales) = {np.var(lengthscales)}")

bias = 0
mean(lengthscales) = 0.4822211266941514
var(lengthscales) = 0.0452161457776703
bias = 1
mean(lengthscales) = 0.4940339909207763
var(lengthscales) = 0.04057249171524807
bias = 2
mean(lengthscales) = 0.4680334234367015
var(lengthscales) = 0.039265876632269596
bias = 3
mean(lengthscales) = 0.47474848670345743
var(lengthscales) = 0.044781663250784025
bias = 4
mean(lengthscales) = 0.47262173562792603
var(lengthscales) = 0.049196601831092854
bias = 5
mean(lengthscales) = 0.4688015973776258
var(lengthscales) = 0.0408343799134774
bias = 6
mean(lengthscales) = 0.5006692411200193
var(lengthscales) = 0.04205789364505844
bias = 7
mean(lengthscales) = 0.4916541673975391
var(lengthscales) = 0.03711713140391075
bias = 8
mean(lengthscales) = 0.4918511826752161
var(lengthscales) = 0.04352468685907732
bias = 9
mean(lengthscales) = 0.4808522731582633
var(lengthscales) = 0.0359189694145142
bias = 10
mean(lengthscales) = 0.49685335071876563
var(lengthscales) = 0.039529013699686345
bias = 11
mean(l

array([[0.31087523]])

In [77]:
# "d" doesn't matter (here is S^{49})

k1 = Matern(length_scale=2.07, nu=0.5)
k2 = NTK(depth = 3, c = 2.0, bias = 2.3)


x2 = np.random.randint(0,100,50).reshape(1,-1)
y2 = np.random.randint(0,100,50).reshape(1,-1)

x2 = normalize(x2)
y2 = normalize(y2)

print(k1(x2,y2))
print(k2(x2,y2))

[[0.73139184]]
[[0.73039979]]
